### ISSUE TITLE
Tests do not compile with data-fix 0.0.6

### ISSUE THREAD

**Issue by rickynils** [haskell-nix/hnix#65]
It looks like the `data-fix` bound needs to be set to `>= 0.0.7`. With `data-fix 0.0.6` I get the following build error:

```
[1 of 3] Compiling ParserTests      ( tests/ParserTests.hs, dist/build/hnix-tests/hnix-tests-tmp/ParserTests.dyn_o )

tests/ParserTests.hs:340:23: error:
    • No instance for (Data.Functor.Classes.Eq1 NExprF)
        arising from a use of ‘assertEqual’
    • In the expression:
        assertEqual ("Parsing data file " ++ file) expected actual
      In a case alternative:
          Success actual
            -> assertEqual ("Parsing data file " ++ file) expected actual
      In a stmt of a 'do' block:
        case res of {
          Success actual
            -> assertEqual ("Parsing data file " ++ file) expected actual
          Failure err
            -> assertFailure
               $ "Unexpected error parsing data file `"
                 ++ file ++ "':\n" ++ show err }

```

**Comment by jwiegley** [comment]
It is set to `>= 0.0.7` now.
